"""Caching for adapter fetch results.

This module provides an in-memory cache to avoid redundant fetches from
external resources when the same query is repeated.
"""

from __future__ import annotations

import hashlib
import json
from typing import Any

from sash.resources.models import LexicalItem


class AdapterCache:
    """In-memory cache for adapter fetch results.

    The cache stores results keyed by a hash of query parameters. This avoids
    redundant fetches when the same query is made multiple times.

    Examples
    --------
    >>> cache = AdapterCache()
    >>> items = [LexicalItem(lemma="walk", pos="VERB")]
    >>> key = cache.make_key("glazing", query="walk", language_code="en")
    >>> cache.set(key, items)
    >>> cached = cache.get(key)
    >>> cached == items
    True
    """

    def __init__(self) -> None:
        """Initialize empty cache.

        Examples
        --------
        >>> cache = AdapterCache()
        >>> len(cache._cache)
        0
        """
        self._cache: dict[str, list[LexicalItem]] = {}

    def get(self, key: str) -> list[LexicalItem] | None:
        """Get cached result.

        Parameters
        ----------
        key : str
            Cache key generated by make_key().

        Returns
        -------
        list[LexicalItem] | None
            Cached items if key exists, None otherwise.

        Examples
        --------
        >>> cache = AdapterCache()
        >>> cache.get("nonexistent")
        None
        """
        return self._cache.get(key)

    def set(self, key: str, items: list[LexicalItem]) -> None:
        """Cache result.

        Parameters
        ----------
        key : str
            Cache key generated by make_key().
        items : list[LexicalItem]
            Items to cache.

        Examples
        --------
        >>> cache = AdapterCache()
        >>> items = [LexicalItem(lemma="walk")]
        >>> cache.set("key1", items)
        >>> cache.get("key1") == items
        True
        """
        self._cache[key] = items

    def clear(self) -> None:
        """Clear entire cache.

        Examples
        --------
        >>> cache = AdapterCache()
        >>> cache.set("key1", [])
        >>> cache.clear()
        >>> cache.get("key1")
        None
        """
        self._cache.clear()

    def make_key(
        self, adapter_name: str, query: str | None = None, **kwargs: Any
    ) -> str:
        """Generate cache key from query parameters.

        Create a deterministic hash key from adapter name, query, and
        additional parameters. Same inputs always produce same key.

        Parameters
        ----------
        adapter_name : str
            Name of the adapter (e.g., "glazing", "unimorph").
        query : str | None
            Query string.
        **kwargs : Any
            Additional query parameters (e.g., language_code, pos).

        Returns
        -------
        str
            Cache key (hexadecimal hash string).

        Examples
        --------
        >>> cache = AdapterCache()
        >>> key1 = cache.make_key("glazing", query="walk", language_code="en")
        >>> key2 = cache.make_key("glazing", query="walk", language_code="en")
        >>> key1 == key2
        True
        >>> key3 = cache.make_key("glazing", query="run", language_code="en")
        >>> key1 != key3
        True
        """
        # Create deterministic dict for hashing
        params = {"adapter": adapter_name, "query": query, **kwargs}
        # Sort keys for deterministic serialization
        serialized = json.dumps(params, sort_keys=True)
        # Return SHA256 hash
        return hashlib.sha256(serialized.encode()).hexdigest()
