import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    // Plugins
    "plugins/rating": "src/plugins/rating.ts",
    "plugins/forced-choice": "src/plugins/forced-choice.ts",
    "plugins/cloze-dropdown": "src/plugins/cloze-dropdown.ts",
    // Library
    "lib/list-distributor": "src/lib/list-distributor.ts",
    "lib/randomizer": "src/lib/randomizer.ts",
    // Slopit bundle (behavioral capture)
    "slopit-bundle": "src/slopit/index.ts",
  },
  format: ["esm"],
  dts: false, // browser code, no type exports needed
  sourcemap: true,
  clean: true,
  target: "es2020",
  splitting: false,
  treeshake: true,
  minify: false,
  external: ["jspsych"],
  // Generate IIFE bundles for browser usage
  esbuildOptions(options) {
    options.banner = {
      js: "/* @bead/jspsych-deployment - Generated by bead */",
    };
  },
});
