"""Shell completion generators for the bead CLI.

This module provides commands for generating and installing shell completion
scripts for bash, zsh, and fish shells.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import click
from rich.console import Console

from bead.cli.utils import print_error, print_info, print_success

console = Console()


@click.group()
def completion() -> None:
    """Generate shell completion scripts.

    Provides tab completion for bead commands in bash, zsh, and fish shells.

    Examples
    --------
    Generate bash completion:
        $ bead completion bash > ~/.bash_completion.d/bead

    Generate zsh completion:
        $ bead completion zsh > ~/.zsh/completion/_bead

    Generate fish completion:
        $ bead completion fish > ~/.config/fish/completions/bead.fish

    Auto-install for current shell:
        $ bead completion install
    """


@completion.command()
def bash() -> None:
    """Generate bash completion script.

    Outputs a bash completion script that can be sourced in your shell
    configuration or installed to /etc/bash_completion.d/.

    Examples
    --------
    Install for current user:
        $ bead completion bash > ~/.bash_completion.d/bead
        $ source ~/.bash_completion.d/bead

    Install system-wide (requires sudo):
        $ sudo bead completion bash > /etc/bash_completion.d/bead

    Add to .bashrc:
        $ bead completion bash >> ~/.bashrc
    """
    # Generate bash completion using Click's built-in support
    completion_script = """
# Bash completion for bead
# Generated by bead completion bash

_bead_completion() {
    local IFS=$'\\n'
    local response

    response=$(env COMP_WORDS="${COMP_WORDS[*]}" COMP_CWORD=$COMP_CWORD _BEAD_COMPLETE=bash_complete bead 2>/dev/null)

    for completion in $response; do
        IFS=',' read type value <<< "$completion"

        if [[ $type == 'dir' ]]; then
            COMPREPLY=()
            compopt -o dirnames
        elif [[ $type == 'file' ]]; then
            COMPREPLY=()
            compopt -o default
        elif [[ $type == 'plain' ]]; then
            COMPREPLY+=($value)
        fi
    done

    return 0
}

complete -o nosort -F _bead_completion bead
"""
    click.echo(completion_script)

    # Print hints to stderr
    sys.stderr.write("\n# Bash completion script generated\n")
    sys.stderr.write("# Install with: bead completion bash > ~/.bash_completion.d/bead\n")


@completion.command()
def zsh() -> None:
    """Generate zsh completion script.

    Outputs a zsh completion script that can be placed in your $fpath.

    Examples
    --------
    Install for current user:
        $ mkdir -p ~/.zsh/completion
        $ bead completion zsh > ~/.zsh/completion/_bead

    Add to .zshrc if not already present:
        $ echo 'fpath=(~/.zsh/completion $fpath)' >> ~/.zshrc
        $ echo 'autoload -Uz compinit && compinit' >> ~/.zshrc

    System-wide install (requires sudo):
        $ sudo bead completion zsh > /usr/share/zsh/site-functions/_bead
    """
    # Generate zsh completion using Click's built-in support
    completion_script = """#compdef bead

# Zsh completion for bead
# Generated by bead completion zsh

_bead() {
    local -a completions
    local -a completions_with_descriptions
    local -a response
    (( ! $+commands[bead] )) && return 1

    response=("${(@f)$(env COMP_WORDS="${words[*]}" COMP_CWORD=$((CURRENT-1)) _BEAD_COMPLETE=zsh_complete bead 2>/dev/null)}")

    for type key descr in ${response}; do
        if [[ "$type" == "plain" ]]; then
            if [[ "$descr" == "_" ]]; then
                completions+=("$key")
            else
                completions_with_descriptions+=("$key":"$descr")
            fi
        elif [[ "$type" == "dir" ]]; then
            _path_files -/
        elif [[ "$type" == "file" ]]; then
            _path_files -f
        fi
    done

    if [ -n "$completions_with_descriptions" ]; then
        _describe -V unsorted completions_with_descriptions -U
    fi

    if [ -n "$completions" ]; then
        compadd -U -V unsorted -a completions
    fi
}

compdef _bead bead
"""
    click.echo(completion_script)

    # Print hints to stderr
    sys.stderr.write("\n# Zsh completion script generated\n")
    sys.stderr.write("# Install with: bead completion zsh > ~/.zsh/completion/_bead\n")


@completion.command()
def fish() -> None:
    """Generate fish completion script.

    Outputs a fish completion script for the fish shell.

    Examples
    --------
    Install for current user:
        $ bead completion fish > ~/.config/fish/completions/bead.fish

    Reload completions:
        $ source ~/.config/fish/completions/bead.fish
    """
    # Generate fish completion using Click's built-in support
    completion_script = """# Fish completion for bead
# Generated by bead completion fish

function __fish_bead_complete
    set -lx COMP_WORDS (commandline -opc)
    set -lx COMP_CWORD (count $COMP_WORDS)
    set -lx _BEAD_COMPLETE fish_complete
    bead 2>/dev/null
end

complete -c bead -f -a "(__fish_bead_complete)"
"""
    click.echo(completion_script)

    # Print hints to stderr
    sys.stderr.write("\n# Fish completion script generated\n")
    sys.stderr.write("# Install with: bead completion fish > ~/.config/fish/completions/bead.fish\n")


@completion.command()
def install() -> None:
    """Auto-detect shell and install completion.

    Detects the current shell from the SHELL environment variable and
    installs the appropriate completion script automatically.

    Examples
    --------
    Auto-install for current shell:
        $ bead completion install

    This command will:
    1. Detect your current shell (bash, zsh, or fish)
    2. Generate the appropriate completion script
    3. Install it to the standard location
    4. Update your shell configuration if needed
    """
    # Detect shell
    shell_path = os.environ.get("SHELL", "")
    shell_name = Path(shell_path).name if shell_path else ""

    if not shell_name:
        print_error("Could not detect shell from $SHELL environment variable")
        print_info("Use specific commands: bead completion bash|zsh|fish")
        sys.exit(1)

    console.print(f"[cyan]Detected shell: {shell_name}[/cyan]")

    try:
        if shell_name == "bash":
            _install_bash()
        elif shell_name == "zsh":
            _install_zsh()
        elif shell_name == "fish":
            _install_fish()
        else:
            print_error(f"Unsupported shell: {shell_name}")
            print_info("Supported shells: bash, zsh, fish")
            sys.exit(1)
    except Exception as e:
        print_error(f"Installation failed: {e}")
        print_info("Try manual installation with: bead completion " + shell_name)
        sys.exit(1)


def _install_bash() -> None:
    """Install bash completion script."""
    home = Path.home()
    completion_dir = home / ".bash_completion.d"
    completion_file = completion_dir / "bead"

    # Create directory if needed
    completion_dir.mkdir(parents=True, exist_ok=True)

    # Generate and write completion script
    result = subprocess.run(
        ["bead", "completion", "bash"],
        capture_output=True,
        text=True,
        check=True,
    )

    completion_file.write_text(result.stdout)
    print_success(f"Installed bash completion: {completion_file}")

    # Check if sourced in .bashrc
    bashrc = home / ".bashrc"
    if bashrc.exists():
        bashrc_content = bashrc.read_text()
        source_line = f"source {completion_file}"

        if source_line not in bashrc_content:
            console.print("\n[yellow]Add to .bashrc:[/yellow]")
            console.print(f"  echo '{source_line}' >> ~/.bashrc")
            console.print("  source ~/.bashrc")
        else:
            print_info("Already sourced in .bashrc")
    else:
        console.print("\n[yellow]Add to .bashrc:[/yellow]")
        console.print(f"  echo 'source {completion_file}' >> ~/.bashrc")
        console.print("  source ~/.bashrc")


def _install_zsh() -> None:
    """Install zsh completion script."""
    home = Path.home()
    completion_dir = home / ".zsh" / "completion"
    completion_file = completion_dir / "_bead"

    # Create directory if needed
    completion_dir.mkdir(parents=True, exist_ok=True)

    # Generate and write completion script
    result = subprocess.run(
        ["bead", "completion", "zsh"],
        capture_output=True,
        text=True,
        check=True,
    )

    completion_file.write_text(result.stdout)
    print_success(f"Installed zsh completion: {completion_file}")

    # Check if fpath configured in .zshrc
    zshrc = home / ".zshrc"
    if zshrc.exists():
        zshrc_content = zshrc.read_text()
        fpath_line = "fpath=(~/.zsh/completion $fpath)"
        compinit_line = "autoload -Uz compinit && compinit"

        needs_update = False
        if fpath_line not in zshrc_content:
            console.print("\n[yellow]Add to .zshrc:[/yellow]")
            console.print(f"  echo '{fpath_line}' >> ~/.zshrc")
            needs_update = True

        if compinit_line not in zshrc_content:
            console.print(f"  echo '{compinit_line}' >> ~/.zshrc")
            needs_update = True

        if needs_update:
            console.print("  source ~/.zshrc")
        else:
            print_info("Already configured in .zshrc")
    else:
        console.print("\n[yellow]Add to .zshrc:[/yellow]")
        console.print("  echo 'fpath=(~/.zsh/completion $fpath)' >> ~/.zshrc")
        console.print("  echo 'autoload -Uz compinit && compinit' >> ~/.zshrc")
        console.print("  source ~/.zshrc")


def _install_fish() -> None:
    """Install fish completion script."""
    home = Path.home()
    completion_dir = home / ".config" / "fish" / "completions"
    completion_file = completion_dir / "bead.fish"

    # Create directory if needed
    completion_dir.mkdir(parents=True, exist_ok=True)

    # Generate and write completion script
    result = subprocess.run(
        ["bead", "completion", "fish"],
        capture_output=True,
        text=True,
        check=True,
    )

    completion_file.write_text(result.stdout)
    print_success(f"Installed fish completion: {completion_file}")

    console.print("\n[yellow]Reload completions:[/yellow]")
    console.print(f"  source {completion_file}")
    print_info("Or restart your shell")
